//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string Adress_From { get; set; }
        public string Adress_Where { get; set; }
        public string Time { get; set; }
        public string Price { get; set; }
        public int AutoId { get; set; }
        public int DriverId { get; set; }
        public int ClientId { get; set; }
    
        public virtual Auto Auto { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Client Client { get; set; }
    }
}
